trigger:
- master

variables:
  vmImageName: 'ubuntu-latest'
  environmentName: 'dev'
  npm_config_cache: $(Pipeline.Workspace)/.npm
  azureSubscription: 'AzurePipeline'
  
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.x'
      displayName: 'Install Node.js'

    - task: Cache@2
      inputs:
        key: 'npm | "$(Agent.OS)" | package-lock.json'
        restoreKeys: |
          npm | "$(Agent.OS)"
        path: $(npm_config_cache)
      displayName: 'Cache npm'

    - script: npm ci
      displayName: 'Install and remove cached node_modules'

    - task: Cache@2
      inputs:
        key: next | "$(Agent.OS)" | package-lock.json
        path: '$(System.DefaultWorkingDirectory)/.next/cache'
      displayName: 'Cache .next/cache'

    - script: npm run build
      displayName: 'Build'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        ArtifactName: 'drop'

- stage: Test
  displayName: Test stage
  dependsOn: Build
  condition: succeeded()
  jobs:
    - job: Test
      displayName: Test
      steps:
        - script: npm run lint
          displayName: 'Run Linting'
        - script: npm run format
          displayName: 'Run Prettier'
        - script: npm run test
          displayName: 'Run jest'

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Test
  condition: succeeded()
    
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureSubscription)
              appType: 'webAppLinux'
              appName: 'your-awesome-app-name'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'