trigger:
  branches:
    include:
      - master

variables:
  - group: bicepVariables 

parameters:
  - name: environment
    type: string
    default: 'Dev'
    values:
      - 'Dev'
      - 'Test'
      - 'Prod'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: PreCommitChecks
  displayName: 'Pre-commit Checks'
  steps:
    - task: Cache@2
      inputs:
        key: 'node | "$(Agent.OS)" | package-lock.json'
        restoreKeys: |
          node | "$(Agent.OS)"
        path: '$(Pipeline.Workspace)/.npm'
      displayName: 'Cache npm'

    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: npm ci
      displayName: 'Install Dependencies'

    - script: npx next lint
      displayName: 'Run Linting'

    - script: npm run format
      displayName: 'Run Prettier'

- job: Build
  dependsOn: PreCommitChecks
  displayName: 'Build and Package'
  steps:
    - task: Cache@2
      inputs:
        key: 'node | "$(Agent.OS)" | package-lock.json'
        restoreKeys: |
          node | "$(Agent.OS)"
        path: '$(Pipeline.Workspace)/.npm'
      displayName: 'Cache npm'

    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: npm ci
      displayName: 'Install Dependencies'

    - script: npm run build
      displayName: 'Build Project'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '.next'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/nextjsapp.zip'
        replaceExistingArchive: true

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/nextjsapp.zip'
        artifact: 'drop'

- job: IntegrationTests
  dependsOn: Build
  displayName: 'Run Integration Tests'
  steps:
    - task: Cache@2
      inputs:
        key: 'node | "$(Agent.OS)" | package-lock.json'
        restoreKeys: |
          node | "$(Agent.OS)"
        path: '$(Pipeline.Workspace)/.npm'
      displayName: 'Cache npm'

    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - script: npm ci
      displayName: 'Install Dependencies'

    - script: npx jest
      displayName: 'Run Integration Tests'

- deployment: Deploy
  displayName: 'Deploy to $(environment) Environment'
  environment: $(environment)
  dependsOn: IntegrationTests
  strategy:
    runOnce:
      preDeployApprovals:
        - name: 'Approvers'
          reviewers:
            - email@example.com
      deploy:
        steps:
        - download: current
          artifact: 'drop'
          
        - task: AzureWebApp@1
          inputs:
            azureSubscription: '$(azureServiceConnection)'
            appName: '$(webAppName)'
            package: '$(Pipeline.Workspace)/drop/nextjsapp.zip'
