trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: bicepVariables

stages:
- stage: DeployBicep
  jobs:
  - deployment: DeployBicep
    environment: 'BicepEnvironment'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              azureResourceManagerConnection: $(azureServiceConnection)
              action: 'Create Or Update Resource Group'
              resourceGroupName: $(resourceGroupName)
              location: 'northeurope'
              templateLocation: 'Linked artifact'
              csmFile: 'main.bicep'
              csmParametersFile: 'main.parameters.json'
            displayName: 'Deploy Bicep File'